# Generated by Django 4.2.8 on 2024-10-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'verbose_name': 'Website visit', 'verbose_name_plural': 'Website visits'},
        ),
        migrations.AddField(
            model_name='visitor',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
